// Client-safe public API. Never re-export services/ from here.
export { getGardenStats } from './actions/getGardenStats'
export { getProgressByDecks } from './actions/getProgressByDecks'
export { getStreak } from './actions/getStreak'
export { submitDrillResult } from './actions/submitDrillResult'
export { StreakBadge } from './components/StreakBadge'
export { DrillSubmissionDto, type DrillSubmission } from './dto/DrillSubmissionDto'
export type { DeckProgress } from './lib/deckProgress'
export type { GardenStats, GardenStatsWithStreak, GardenTree } from './lib/gardenStats'
export { nextStreakMilestone, STREAK_MILESTONES, streakMilestone, type Streaks } from './lib/streak'
export { MASTERY_NAMES, MAX_MASTERY, nextMastery } from './lib/masteryRules'
export type { DrillResult, GradedAnswer, MasteryLevel } from './types'
